app:
  title: Shopify_test_discount_function
  application_developer: shopify
  kind: oauth2
  embedded: true
  api_key: x-shopify_test_discount_function-key
  shared_secret: x-shopify_test_discount_function-secret
  is_channel: false
  visible: true
  admin_featured: false
  preauthorized_access_scope_str: read_customers, read_discounts, read_products, read_marketing_events, write_files, read_files, read_content,write_content, write_discounts
  webhook_api_version: 2022-07
  beta_flags:
    - brand_setting_graphql_api
    - script_discount_types_api
    - extensible_discounts_api_extensions
    - function_1p_internal
    - fulfillment_constraints_api
  scope_permissions:
    - read_internal_graphql_admin_api
    - read_checkout_settings
    - read_brand
    - read_online_store
    - write_files
    - read_files

shop:
  id: 9
  beta_flags:
    - online_store_color_schemes_ga
    - checkout_one_server_validation_functions
