name = "order-discount"
type = "order_discounts"
api_version = "2023-01"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/order/:functionId/new"
details = "/order/:functionId/:id"
